kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.21.1
- role: worker
  image: kindest/node:v1.21.1
- role: worker
  image: kindest/node:1.21.1-krustlet-v1.0.0-alpha.1-systemd
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "krustlet=true,kubernetes.io/arch=wasm32-wasi"
        register-with-taints: "kubernetes.io/arch=wasm32-wasi:NoSchedule,kubernetes.io/arch=wasm32-wasi:NoExecute"
